Drop support for precise, trusty, xenial
swiftstack/vagrant-swift-all-in-one pull request #156
Opened 2024-01-18 20:22 UTC by tipabu

Looks like deadsnakes only supports focal & jammy at the moment:

See https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

Good news is, we can still test py2 on focal just fine. py36 testing maybe gets more difficult, though...

2024-01-19 01:47 UTC, matthewoliver commented
Clean up sounds good. And if we ever need to go back we always have git history.

Doing a quick git grep:

```
$ git grep bionic
Vagrantfile:# Note: 18.04/bionic requires Vagrant 2.02 or newer because 18.04 ships without ifup/ifdown by default.
Vagrantfile:  "bionic" => "http://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64-vagrant.box",
cookbooks/swift/recipes/setup.rb:  "bandit==1.5.1",  # pin bandit to avoid pyyaml issues on bionic (at least)
localrc-template:export VAGRANT_BOX=jammy  # precise, xenial, bionic, etc.
```
We seem to pin bandit, does that mean we might be able to stop pinning this as well?

2024-05-20 19:01 UTC, tipabu commented
> We seem to pin bandit, does that mean we might be able to stop pinning this as well?

Keeping it for now, as I'm keeping bionic support for now. Upstream, we should seriously consider dropping py36 support as we drop py27.

2025-02-07 18:23 UTC, clayg requested changes
this is doing a lot; more than I might expect - but also since it's been awhile I wonder if at this point we shouldn't try to remove the old distros and py2 at the same time?

Also it didn't work for me:

```
==> default: * execute[live dangerously] action run
==> default: [2025-02-07T18:20:54+00:00] INFO: execute[live dangerously] ran successfully
==> default:     
==> default: - execute echo '[global]' > /etc/pip.conf && echo 'break-system-packages = True' >> /etc/pip.conf
==> default:   
==> default: * execute[upgrade pip] action run
==> default: 
==> default:     [execute] Requirement already satisfied: pip>=8.0.2 in /usr/lib/python3/dist-packages (24.0)
==> default:               Collecting pip>=8.0.2
==> default:               
==> default:   Downloading pip-25.0-py3-none-any.whl.metadata (3.7 kB)
==> default:               
==> default: Downloading pip-25.0-py3-none-any.whl (1.8 MB)
==> default:                  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.4 MB/s eta 0:00:00
==> default:               Installing collected packages: pip
==> default:                 Attempting uninstall: pip
==> default:                   Found existing installation: pip 24.0
==> default:               
==> default: ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.
==> default:     
==> default:     
==> default: ================================================================================
==> default:     
==> default: Error executing action `run` on resource 'execute[upgrade pip]'
==> default:     
==> default: ================================================================================
==> default:     
==> default:     
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default:     
==> default: ------------------------------------
==> default:     Expected process to exit with [0], but received '1'
==> default:     ---- Begin output of pip install --upgrade 'pip>=8.0.2' ----
==> default:     STDOUT: Requirement already satisfied: pip>=8.0.2 in /usr/lib/python3/dist-packages (24.0)
==> default:     Collecting pip>=8.0.2
==> default:       Downloading pip-25.0-py3-none-any.whl.metadata (3.7 kB)
==> default:     Downloading pip-25.0-py3-none-any.whl (1.8 MB)
==> default:        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.4 MB/s eta 0:00:00
==> default:     Installing collected packages: pip
==> default:       Attempting uninstall: pip
==> default:         Found existing installation: pip 24.0
==> default:     STDERR: ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.
==> default:     ---- End output of pip install --upgrade 'pip>=8.0.2' ----
==> default:     Ran pip install --upgrade 'pip>=8.0.2' returned 1
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/swift/recipes/setup.rb
==> default:     
==> default:     144: execute "upgrade pip" do
==> default:     145:   command "pip install --upgrade 'pip>=8.0.2'"
==> default:     146: end
==> default:     147: 
==> default:     
==> default:     
==> default: Compiled Resource:
==> default:     
==> default: ------------------
==> default:     
==> default: # Declared in /var/chef/cache/cookbooks/swift/recipes/setup.rb:144:in `from_file'
==> default:     
==> default:     
==> default: execute("upgrade pip") do
==> default:     
==> default:   action [:run]
==> default:     
==> default:   default_guard_interpreter :execute
==> default:       command "pip install --upgrade 'pip>=8.0.2'"
==> default:       declared_type :execute
==> default:       cookbook_name "swift"
==> default:       recipe_name "setup"
==> default:     end
==> default:     
==> default:     System Info:
==> default:     ------------
==> default:     chef_version=18.6.2
==> default:     platform=ubuntu
==> default:     platform_version=24.04
==> default:     ruby=ruby 3.1.6p260 (2024-05-29 revision a777087be6) [x86_64-linux]
==> default:     program_name=/usr/bin/chef-solo
==> default:     executable=/opt/chef-workstation/bin/chef-solo
==> default:     
==> default: [2025-02-07T18:20:56+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: Running handlers:
==> default: [2025-02-07T18:20:56+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2025-02-07T18:20:56+00:00] ERROR: Exception handlers complete
==> default: Infra Phase failed. 29 resources updated in 02 minutes 09 seconds
==> default: [2025-02-07T18:20:56+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2025-02-07T18:20:56+00:00] FATAL: ---------------------------------------------------------------------------------------
==> default: [2025-02-07T18:20:56+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
==> default: [2025-02-07T18:20:56+00:00] FATAL: ---------------------------------------------------------------------------------------
==> default: [2025-02-07T18:20:56+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[upgrade pip] (swift::setup line 144) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of pip install --upgrade 'pip>=8.0.2' ----
==> default: STDOUT: Requirement already satisfied: pip>=8.0.2 in /usr/lib/python3/dist-packages (24.0)
==> default: Collecting pip>=8.0.2
==> default:   Downloading pip-25.0-py3-none-any.whl.metadata (3.7 kB)
==> default: Downloading pip-25.0-py3-none-any.whl (1.8 MB)
==> default:    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 3.4 MB/s eta 0:00:00
==> default: Installing collected packages: pip
==> default:   Attempting uninstall: pip
==> default:     Found existing installation: pip 24.0
==> default: STDERR: ERROR: Cannot uninstall pip 24.0, RECORD file not found. Hint: The package was installed by debian.
==> default: ---- End output of pip install --upgrade 'pip>=8.0.2' ----
==> default: Ran pip install --upgrade 'pip>=8.0.2' returned 1
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

2025-02-07 18:23 UTC, clayg commented on cookbooks/swift/recipes/setup.rb
> -    "python-dev",
this at least seems required for noble; there is no legacy `python-dev` package anymore - `python3-dev` FTW Huzzah!

2026-05-11 21:06 UTC, closed without merging